init: Prevent crash if the player doesn't exist
If the configured player have been uninstalled before specifying a new one you could end locked out of mpsyt because of the program crashing to FileNotFoundError.
Handle this exception and still allow to enter the main interface to change the player without having to reinstall the older one.

Traceback (most recent call last):
  File "/home/eskuero/.local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/home/eskuero/.local/lib/python3.5/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/home/eskuero/.local/lib/python3.5/site-packages/mps_youtube/init.py", line 59, in init
    assign_player(config.PLAYER.get)  # Player is not assigned when config is loaded
  File "/home/eskuero/.local/lib/python3.5/site-packages/mps_youtube/util.py", line 544, in assign_player
    g.PLAYER_OBJ = pl(player)
  File "/home/eskuero/.local/lib/python3.5/site-packages/mps_youtube/players/mplayer.py", line 27, in __init__
    self.mplayer_version = _get_mplayer_version(player)
  File "/home/eskuero/.local/lib/python3.5/site-packages/mps_youtube/players/mplayer.py", line 238, in _get_mplayer_version
    o = subprocess.check_output([exename]).decode()
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'mplayer'